### PR TITLE
Tags and Includes

### PR DESCRIPTION
**Pull request by jasonjoh**
Implemented tagging and includes. See markdown-customizations.md in the docs folder for details.

### CODE REVIEW

**Comment by jasonjoh** [comment]
@rgregg I can't view the AppVeyor data, so I'm not sure why this build failed.

**Comment by rgregg** [comment]
@jasonjoh The error is this:

Writers\IPublishOptions.cs(88,62): error CS0840: 'ApiDocs.Validation.Writers.DefaultPublishOptions.PageParameterDict.get' must declare a body because it is not marked abstract or extern. Automatically implemented properties must define both get and set accessors. [C:\projects\markdown-scanner\ApiDocs.Validation\ApiDocs.Validation.csproj]

**Comment by jasonjoh** [comment]
Interesting. Visual Studio doesn't seem to care about this, I wonder if AppVeyor is using a different compiler or different options. I added the set accessor, so we'll see if it passes. Can you give me read access to the AppVeyor project in case it fails again?

**Comment by rgregg** [comment]
I just recreated the appveyor config so the project is public now. Unfortunately that blew away the existing build history, so you'll need to tickle your commit history to get it to build this PR again.

**Pull request merged**
